apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: keycloak
  name: keycloak-creds
type: Opaque
stringData:
  POSTGRESQL_USER: keycloakuser
  POSTGRESQL_PASSWORD: K3yC!0@kAM34
