apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: apps-wildcard-cert 
spec:
  isCA: false
  commonName: "apps.<cluster-domain>" 
  secretName: apps-wildcard-cert 
  dnsNames:
  - "apps.<cluster-domain>" 
  - "*.apps.<cluster-domain>" 
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer